name: chatapp
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  universal_html: ^2.2.4
  get: ^4.6.6
  rename: ^3.0.2
  shared_preferences: ^2.5.1
  firebase_core: ^3.12.1
  firebase_analytics: ^11.4.4
  flutter_chat_core: ^2.4.0
  flutter_chat_ui: ^2.3.1
  hexcolor: ^3.0.1
  intl: ^0.20.2
  chatview: ^2.4.1
  file_picker: ^10.1.9
  audioplayers: ^6.4.0
  path: ^1.9.1
  just_audio: ^0.10.3
  syncfusion_flutter_pdfviewer: ^29.2.7
  # permission_handler: ^12.0.0+1
  flutter_sound: ^9.28.0
  flutter_spinkit: ^5.2.1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  audio_waveforms: ^1.3.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/locales/
